elasticsearch:
  es_index_name: sample-index
  es_ai_index_name: sample-index-ai
ogcapi:
  host: "http://localhost:8080/"
  endpoint: "api/v1/ogc/collections"
  query: "?properties=id,title,description,statement,themes,status&filter=page_size%3D"
  page_size: 100
  sleep_time: 3
  max_retries: 3
  timeout: 10
mlflow:
  port: 53000
  gateway: "http://127.0.0.1:53001"
application:
  port: 8000
  reload: True
  max_timeout: 180
  sse_interval: 10
model:
  description_formatting:
    model: llama3
    temperature: 0.0
    max_tokens: 4000
    response_key: "summaries.ai:description"
