elasticsearch:
  es_index_name: es-indexer-production
  es_ai_index_name: es-indexer-production-ai
ogcapi:
  host: "https://ogcapi.production.aodn.org.au/"
  endpoint: "api/v1/ogc/collections"
  query: "?properties=id,title,description&filter=page_size%3D"
  page_size: 11
  sleep_time: 3
  max_tries: 3
  timeout: 10
mlflow:
  port: 53000
  gateway: "http://127.0.0.1:53001"
application:
  port: 8000
  reload: False
  max_timeout: 120
  sse_interval: 10
model:
  description_formatting:
    model: gpt-4o-mini
    temperature: 0.01
    max_tokens: 10000
    response_key: "summaries.ai:description"
